### ISSUE TITLE
rename master branch to main

### ISSUE THREAD

**Issue by josharian** [pkg/diff#22]
need to check what impact this has on go modules

**Comment by mvdan** [comment]
FYI, this would have zero impact to builds and existing go.mod files, because those always pin to specific tags/commits, and never branches. The only thing that would break is humans doing `go get github.com/pkg/diff@master` to get the latest master version, sincce now that would have to be `@main`. That doesn't seem like a big problem to me though, as I see it part of the general trend to teach people to use "main" instead.

**Comment by josharian** [comment]
Done.
